# DopaDiff Data Analysis. V1
# Generated by Q. Jia. 1/13/15

# Variables
cutoff = 4.96

# Libraries
library("JBTools")

# Inputs
data <- read.table("~/Desktop/lammps/11/log.lammps.txt")
names(data) = c ("steps", "graphene_z", "DA_z", "DA_x", "DA_y")

# Computes the distance btw DA and graphene
distance <- data[, 3] - data[, 2]
# histogram <- hist(distance, breaks = 1000)

# Returns the longest sequence on the surface
surface <- (distance < cutoff)
longest <- seqLongest(surface)
temp_x <- data[longest$pos:(longest$pos + longest$size - 1), 4] - data[longest$pos, 4]
temp_y <- data[longest$pos:(longest$pos + longest$size - 1), 5] - data[longest$pos, 5]

# Calculates the msd over time
msd <- (temp_x * temp_x) + (temp_y * temp_y)
jpeg("~/Desktop/lammps/11/msd1.jpg")
plot(1:longest$size, msd)
dev.off()

# Calculates the second longest sequence
surface[longest$pos:(longest$pos + longest$size - 1)] <- FALSE
sec_longest <- seqLongest(surface)
temp_x <- data[sec_longest$pos:(sec_longest$pos + sec_longest$size - 1), 4] - data[sec_longest$pos, 4]
temp_y <- data[sec_longest$pos:(sec_longest$pos + sec_longest$size - 1), 5] - data[sec_longest$pos, 5]
msd <- (temp_x * temp_x) + (temp_y * temp_y)
jpeg("~/Desktop/lammps/11/msd2.jpg")
plot(1:sec_longest$size, msd)
dev.off()

# Calculate the diffusion coeff
iterations <- 150000:longest$size
rate <- msd[150000:longest$size]
fit <- lm (rate ~ iterations)
fit

#############################################
# Returns the longest sequence in the solution
solution <- (distance > cutoff)
longest <- seqLongest(solution)
temp_x <- data[longest$pos:(longest$pos + longest$size - 1), 4] - data[longest$pos, 4]
temp_y <- data[longest$pos:(longest$pos + longest$size - 1), 5] - data[longest$pos, 5]
temp_z <- data[longest$pos:(longest$pos + longest$size - 1), 3] - data[longest$pos, 3]

# Calculates the msd over time
msd <- (temp_x * temp_x) + (temp_y * temp_y) + (temp_z) * (temp_z)
#jpeg("~/Desktop/lammps/11/msd1.jpg")
plot(1:longest$size, msd)
#dev.off()

# Calculate the diffusion coeff
iterations <- 150000:longest$size
rate <- msd[150000:longest$size]
fit <- lm (rate ~ iterations)
fit
